### PR TITLE
Switch from bzImage to kernel for kernel image

### PR DESCRIPTION
**Pull request by justincormack**
This was too architecture specific previously.

Signed-off-by: Justin Cormack <justin.cormack@docker.com>

### CODE REVIEW

**Comment by rneugeba** [comment]
How are we going to handle the transition? Could we check for `bzImage` for sometime if `kernel` is not there? At least for a while?

**Comment by justincormack** [comment]
Yeah, I was thinking I would break it but maybe I will put a transition in.

**Comment by justincormack** [comment]
Ok reworked to support both `kernel` and `bzImage` for now, and also to not require `tar` in the kernel image.

**Comment by rneugeba** [comment]
did you forget to push?

**Comment by justincormack** [comment]
Yes, well I forgot the force as I had rebased

**Comment by justincormack** [comment]
updated

**Pull request merged**
