### PR TITLE
WIP: fix docker run stdin handling

### PR DESCRIPTION
**Pull request by riyazdf**
Opening early to get feedback - thank you @cpuguy83 and @aaronlehmann for the early help but unfortunately it seems like I haven't found my around how to properly pipe input to the container's stdin via the API.

cc @tiborvass since he's offered to help as well :)

Does anything here look astoundingly incorrect?  I'll continue to debug in the meantime.

Signed-off-by: Riyaz Faizullabhoy <riyaz.faizullabhoy@docker.com>

### CODE REVIEW

**Comment by justincormack** [comment]
@riyazdf any update? also needs a rebase.

**Comment by riyazdf** [comment]
@justincormack unfortunately I haven't been able to get to the bottom of this.  Do you spot anything terribly wrong with how I'm consuming the API?

**Comment by ijc25** [comment]
@riyazdf perhaps I'm misreading but it seems you are doing these three things serially/sequentially :
1. copying the supplied input into the container's stdin (the `io.Copy(hijackedResp.Conn, input)`)
2. once the input is exhausted wait for the container to exit (the `cli.ContainerWait(context.Background(), resp.ID)`)
3. reading and discarding the container's stdout, (the `ioutil.ReadAll(hijackedResp.Reader)` bit)

If the container produces sufficient output during stage 1 then it will block because its output pipe is full (and state 3 which drains it has not begun yet) and therefore not consume any further input, so eventually the `io.Copy` will stall on that pipe being full and the whole lot will deadlock. Perhaps the `ioutil.ReadAll(hijackedResp.Reader)` needs to be kicked off as a goroutine before step 1 and step 3 should be instead synchronising on that completing? I suggest synchronising rather than just letting it do its thing to ensure you don't do the defer'd close before things are actually finished.

Separately from that you might want to `shutdown(SHUT_WR)` on `hijackedResp` once the `input` is all consumed, and perhaps `shutdown(SHUT_RD)` once `ioutil.ReadAll(hijackedResp.Reader)` is done.

**Comment by cpuguy83** [comment]
The container will be blocked on stdout/stderr writes if you are not consuming it.
I would move both the stdin copy and the stdout/stderr copy into goroutines and use `ContainerWait` to block the function from returning early.

**Comment by justincormack** [comment]
Note that this is fairly low priority as I am working on removing all use of `docker` here anyway (I have a containerd branch and am working on using `linuxkit` to build the parts that currently use docker

**Comment by riyazdf** [comment]
@justincormack agree, I've been trying small fixes in spare cycles but haven't put much priority behind this.  @ijc25 had a great suggestion to use `*sync.WaitGroup` to get this working, but I haven't had the chance to try it yet.

We can close this if you'd like, since it will be slow-moving unless we want to reprioritize

**Comment by justincormack** [comment]
Lets close for now

**Pull request closed without merging**
