### PR TITLE
Move to Go 1.10

### PR DESCRIPTION
**Pull request by justincormack**
We need the Format exptension in the tar package.

Signed-off-by: Justin Cormack <justin.cormack@docker.com>

### CODE REVIEW

**Comment by justincormack** [comment]
Argh, there is no circleci Go 1.10 image!

**Comment by ijc** [comment]
Arg! Perhaps you can `brew install` it?

**Comment by justincormack** [comment]
We are using Linux, seeing if we can use a container image not a machine image... ah no the test will fail...

**Comment by ijc** [comment]
I think it doesn't have to be a circle specific image, perhaps the usual hub golang image will work?

**Comment by justincormack** [comment]
No we are using the `machine` setup, which only has machine images that currently only has Go 1.9... I need to read the docs but its all a bit horrible

**Comment by ijc** [comment]
The tests will fail because they need docker? You can run a remote docker and configure things to use it see the linuxkit/kubernetes circle config, but I guess the tool doesn't obey `DOCKER_HOST`?

**Comment by justincormack** [comment]
Apparently it does respect remote Docker!

**Pull request merged**
