### PR TITLE
Update dependencies to use sirupsen not Sirupsen

### PR DESCRIPTION
**Pull request by justincormack**
That entailed a few other fixes, eg small Notary API changes.

Signed-off-by: Justin Cormack <justin.cormack@docker.com>

Had to do this on Linux, as despite upgrading to APFS OSX still defaults to case sensitive. You may need to delete and re-clone on OSX...

### CODE REVIEW

**Comment by justincormack** [comment]
@riyazdf could you check the notary changes?

**Comment by riyazdf** [comment]
notary changes LGTM, thanks for updating!

I think the CI might be hung up on some vendored code not passing linting

**Comment by justincormack** [comment]
Sigh, this is a pain. It seems to be partly an issue of Go versions, as `time.Until` is not in earlier versions, but circleci wont update for me...

**Comment by justincormack** [comment]
ah ok, managed to get it to use a newer version of Go...

**Pull request merged**
