### PR TITLE
In the init section use a symlink for /etc/resolv.conf

### PR DESCRIPTION
**Pull request by justincormack**
Unfortunately there are a lot of issues with resolv.conf as we
cannot actually write it into the image from any docker image, as docker will
always have something bind mounted in.

In addition, normally we expect the filesystem to br read only for images
that moby generates, so the actual etc/resolv.conf is likely not to be writeable.

Previously we were adding in a default resolv.conf into every image pointing at
Google's name servers but that is really a bad idea.

Instead, normal images now get an empty default, while images in the `init`
section will get a symlink, currently hard coded to `/run/resolvconf/resolv.conf`
but you can override this with the `files` section to be static or a different
link.

In future, if we have an easy way to build and extract images with user control
of this, we can drop this.

Signed-off-by: Justin Cormack <justin.cormack@docker.com>

### CODE REVIEW

**Comment by ijc** [comment]
For regular (non-`init`) images is the idea that commonly the host `/etc/resolve.conf` would be bound in (along with `/run/resolveconf`)?

**Comment by justincormack** [comment]
Anything that needs a resolver needs `binds: /etc/resolv.conf:/etc/resolv.conf` (or from `/run` just testing what the symlink resolution requirements are). This was already the case in theory but you ended up getting the Google resolver not the host one if you forgot, so you probably didnt notice that it was wrong.

**Comment by justincormack** [comment]
Yes, you can use `binds: /etc/resolv.conf:/etc/resolv.conf` as `runc` resolves symlinks on source paths, so if you override with a static `resolv.conf` in `files` that will work too.

**Comment by ijc** [comment]
Ah good, I didn't think symlinks were resolved, it's much nicer that they are for sure.

**Pull request merged**
