### PR TITLE
implement docker pull using docker API + notary library 

### PR DESCRIPTION
**Pull request by riyazdf**
Implements `docker pull` using the docker API and notary library in order to facilitate docker content trust.  Like the docker implementation, this considers `targets/releases` and `targets` as the canonical roles of trust.  As of now only works with public images on hub (which is the same functionality as the tool today).

Tested with a local `moby build linuxkit.yml`

### CODE REVIEW

**Comment by riyazdf** [comment]
cc @endophage since we've both worked on similar code before

**Comment by justincormack** [comment]
This looks ok to me...

**Comment by justincormack** [comment]
needs a rebase...

**Comment by riyazdf** [comment]
rebased!

**Comment by justincormack** [comment]
Hmm, any chance you could split out the vendor commit and the code change again? Its much easier to read...

**Comment by riyazdf** [comment]
@justincormack sure, done

**Pull request merged**
