### PR TITLE
revendor runc + runtime-spec to match containerd 8e1a04ff9ee3

### PR DESCRIPTION
**Pull request by ijc**
Note that various fields have changed moved around in the JSON as a result:

* `Platform` has been removed.
* `Process` is now a pointer.
* `OOMScoreAdj` has moved into `Process`, from `Linux.Resources` (resolving a
  TODO here).

Also updates golang.org/x/sys which is less critical.

Signed-off-by: Ian Campbell <ian.campbell@docker.com>

### CODE REVIEW

**Comment by justincormack** [comment]
Merged from under the Channel!

**Comment by ijc** [comment]
Attempting to vendor this in https://github.com/linuxkit/linuxkit/pull/2159 highlighted that this breaks the windows build:
```
$ make -j 3 GOOS=windows tmp_moby_bin.tar
...
# github.com/moby/tool/vendor/github.com/opencontainers/runc/libcontainer/user
../../vendor/github.com/opencontainers/runc/libcontainer/user/lookup.go:44: undefined: unix.Getuid
../../vendor/github.com/opencontainers/runc/libcontainer/user/lookup.go:92: undefined: unix.Getgid
```

I'm still investigating what to do, but it seems reasonable that `unix.Getuid` is not on Windows and it seems reasonable for `runc/libcontainer` to rely on it (being Linux only software). Not quite sure where the dependency from moby tool onto this code comes from, I'll chase that down.

**Comment by justincormack** [comment]
Can you add cross build tests here too, so this doesn't repeat if you do a
PR to fix.

**Comment by ijc** [comment]
Closed with #103

**Pull request merged**
