### PR TITLE
Build for Darwin and Windows

### PR DESCRIPTION
**Pull request by ijc**
#102 broke the build on Windows. This PR will fix that and add CI tests.

Currently it just adds the tests, which I expect to fail (getting this bit pushed early since RTT to checking things are OK with CI can take a while...).

Actual tests will follow.

### CODE REVIEW

**Comment by ijc** [comment]
https://github.com/opencontainers/runc/pull/1509 ought to fix the cross compile problem, but CI is also showing that I need to arrange for a go cross compile environment in the CI. Will look at this tomorrow.

**Comment by ijc** [comment]
Dropped the "WIP" although that might depend on ones opinion on temporarily vendoring a PR rather than master of `runc`.

**Comment by justincormack** [comment]
Yeah, this clearly isnt going to get merged, will take a look and see if we want to do this for now or not.

**Comment by justincormack** [comment]
Upstream fix in https://github.com/moby/moby/pull/34040

**Comment by ijc** [comment]
I added a temporary vendor https://github.com/moby/moby/pull/34040 to check it out.

**Comment by justincormack** [comment]
@ijc that PR was merged

**Comment by ijc** [comment]
Updated with a proper vendor of moby/moby master https://github.com/moby/moby/commit/6978a6e25a2e6063f280ec842bd0f3eae99426e1. Compared with the previous temporary vendoring of the branch all that changed was `vendor/github.com/docker/docker/vendor.conf` in a way which didn't affect any transitive vendoring

**Pull request merged**
